{{- if .Values.daemonset.deploy }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "sysdig.fullname" . }}
  labels:
{{ include "sysdig.labels" . | indent 4 }}
data:
  dragent.yaml: |
    new_k8s: true
{{- $clusterName := include "helper-lib.clusterName" . }}
{{- if $clusterName }}
    k8s_cluster_name: {{ $clusterName }}
{{- end }}
{{- if or .Values.secure.enabled .Values.auditLog.enabled }}
    security:
  {{- if .Values.auditLog.enabled }}
      k8s_audit_server_url: {{ .Values.auditLog.auditServerUrl }}
      k8s_audit_server_port: {{ .Values.auditLog.auditServerPort }}
  {{- end }}
  {{- if .Values.secure.enabled }}
      enabled: true
    commandlines_capture:
      enabled: true
    memdump:
      enabled: true
  {{- end }}
{{- end }}
    sysdig_capture_enabled: {{ not .Values.sysdig.disableCaptures }}
{{- if .Values.collectorSettings.collectorHost }}
    collector: {{ .Values.collectorSettings.collectorHost }}
{{- end }}
{{- if .Values.collectorSettings.collectorPort }}
    collector_port: {{ .Values.collectorSettings.collectorPort }}
{{- end }}
{{- if .Values.collectorSettings.ssl }}
    ssl: .Values.collectorSettings.ssl
{{- end }}
{{- if .Values.collectorSettings.sslVerifyCertificate }}
    ssl_verify_certificate: {{ .Values.collectorSettings.sslVerifyCertificate }}
{{- end }}
{{- if .Values.sysdig.settings }}
{{ toYaml .Values.sysdig.settings | indent 4 }}
{{- end }}
{{- if .Values.leaderelection.enable }}
    k8s_delegation_election: true
    k8s_coldstart:
      enabled: true
      enforce_leader_election: true
      namespace: {{ .Release.Namespace}}
{{- end }}
{{- if .Values.prometheus.file }}
  prometheus.yaml: |
{{ toYaml .Values.prometheus.yaml | indent 4 }}
{{- end }}
{{- end }}
