name: Lint and Test Charts

on: pull_request

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.4.0

      - uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.2.0

      - name: Expand templates for CI
        run: |
          find -iname "*.yaml.template" | xargs -L1 -- bash -c 'envsubst < $0 > ${0%.template}'
        shell: bash
        env:
          SECURE_API_TOKEN: ${{ secrets.KUBELAB_SECURE_API_TOKEN }}
          SECURE_AGENT_TOKEN: ${{ secrets.KUBELAB_AGENT_KEY }}

      - name: Run chart-testing (lint)
        run: ct lint

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed_charts=$(ct list-changed | paste -s -d' ' -)
          if [[ -n "$changed_charts" ]]; then
            echo "::set-output name=changed::true"
            echo "::set-output name=changed_charts::$changed_charts"
          fi

      - name: Run kubeval on charts
        env:
          CHANGED_CHARTS: ${{ steps.list-changed.outputs.changed_charts }}
        run: |
          set -ex
          for chart in $CHANGED_CHARTS
          do
            cd $chart
            mkdir gen

            VALUES_FILES=$(find ci/ -iname "*.yaml")
            for VALUES_FILE in $VALUES_FILES
            do
              helm template . -f $VALUES_FILE > gen/rendered.yaml
              docker run -it -v $PWD/gen:/gen garethr/kubeval --ignore-missing-schemas /gen/rendered.yaml
            done

            rm -rf gen
            cd -
          done

      - name: Create kind cluster
        uses: helm/kind-action@v1.2.0
        with:
          wait: 120s
        if: steps.list-changed.outputs.changed == 'true'

      - name: Run chart-testing (install)
        run: ct install
